/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BusinessLogic;
import BL.DataBase;
import BL.Project;
import BL.Task;
import BL.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author johannesriedmueller
 */
public class MainScreenGUI extends javax.swing.JFrame {

    private BusinessLogic bl = new BusinessLogic();
    private Project project;
    private static DateTimeFormatter dtf;

    static {
        dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    }

    public MainScreenGUI(Project project) {
        initComponents();
        this.project = project;
        try {
            updateEveryThing();
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        liUsers.setModel((ListModel<User>) bl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAddUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liUsers = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btAddTask = new javax.swing.JButton();
        btProductBacklog = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 490));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btAddUser.setText("Add User");
        btAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddUserActionPerformed(evt);
            }
        });
        jPanel1.add(btAddUser, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(liUsers);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(533, 25));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        btAddTask.setText("Add Task");
        btAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTaskActionPerformed(evt);
            }
        });
        jPanel3.add(btAddTask);

        btProductBacklog.setText("Change to Product Backlog");
        btProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductBacklogActionPerformed(evt);
            }
        });
        jPanel3.add(btProductBacklog);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserToDataBase(User user) throws SQLException {
        Statement stat = DataBase.getDbInstance().getConn().createStatement();
        String sqlString = String.format("INSERT INTO public.\"User\"(\"UserID\", \"fk_ProjID\", \"Username\") VALUES (DEFAULT, \'%s\', \'%s\');", project.getProjectId(), user.getName());
        stat.executeQuery(sqlString);
        stat.close();
    }

    private String checkUserId(String username) throws SQLException {
        Statement stat = DataBase.getDbInstance().getConn().createStatement();
        String sqlString = String.format("SELECT * FROM public.\"User\" WHERE \"Username\" = \'%s\'", username);
        ResultSet rs = stat.executeQuery(sqlString);
        while (rs.next()) {
            return rs.getString("UserID");
        }
        return "";
    }

    public void updateEveryThing() throws SQLException {
        this.setTitle(project.getName());
        Statement stat = DataBase.getDbInstance().getConn().createStatement();
        String sqlString = String.format("SELECT \"Username\", \"UserID\" FROM public.\"User\" WHERE \"fk_ProjID\" = %s;", project.getProjectId());
        ResultSet rs = stat.executeQuery(sqlString);
        while (rs.next()) {
            bl.add(new User(rs.getString("Username"), rs.getString("UserID")));
        }
    }

    private void addTaskToDataBase(Task task) throws SQLException {
        Statement stat = DataBase.getDbInstance().getConn().createStatement();
        String sqlString = String.format("INSERT INTO public.\"Task\"(\"StartDate\", \"EndDate\", \"fk_ProjID\", \"fk_UserID\", \"TaskName\") VALUES (TO_DATE(\'%s\','DD.MM.YYYY'), TO_DATE(\'%s\','DD.MM.YYYY'), \'%s\', \'%s\', \'%s\');", dtf.format(task.getStartDate()), dtf.format(task.getEndDate()), project.getProjectId(), task.getUser().getUserid(), task.getTaskName());
        stat.executeQuery(sqlString);
        stat.close();
    }

    private void btAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddUserActionPerformed
        String name = JOptionPane.showInputDialog("Please enter a name:");
        User user = new User(name);
        try {
            addUserToDataBase(user);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String userid = "";
        try {
            userid = checkUserId(name);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!userid.equals("")) {
            bl.add(user.setUserid(userid));
        }
    }//GEN-LAST:event_btAddUserActionPerformed

    private void btAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTaskActionPerformed
        TaskDialog dialog = new TaskDialog(this, true, bl.getUsers());
        dialog.setVisible(true);
        if(dialog.isOk()){
            Task task = dialog.getTask();
            try {
                addTaskToDataBase(task);
            } catch (SQLException ex) {
                Logger.getLogger(MainScreenGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            bl.add(task);
        }
    }//GEN-LAST:event_btAddTaskActionPerformed

    private void btProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductBacklogActionPerformed

    }//GEN-LAST:event_btProductBacklogActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTask;
    private javax.swing.JButton btAddUser;
    private javax.swing.JButton btProductBacklog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<User> liUsers;
    // End of variables declaration//GEN-END:variables
}
