/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BusinessLogic;
import BL.Task;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author johannesriedmueller
 */
public class ProductBacklogGUI extends javax.swing.JDialog {

    private BusinessLogic bl;
    private LocalDate currentWeek;
    private DefaultListModel dlmAll = new DefaultListModel();
    private DefaultListModel dlmThisWeek = new DefaultListModel();

    public ProductBacklogGUI(java.awt.Frame parent, boolean modal, BusinessLogic bl, LocalDate currentWeek) {
        super(parent, modal);
        initComponents();
        this.currentWeek = currentWeek;
        this.bl = bl;
        this.setSize(900, 300);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        liAll.setModel(dlmAll);
        liThisWeek.setModel(dlmThisWeek);
        initializeEverything();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmDeleteFromAll = new javax.swing.JPopupMenu();
        miDeleteFromAll = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liThisWeek = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liAll = new javax.swing.JList<>();
        btExportCSV = new javax.swing.JButton();

        miDeleteFromAll.setText("Delete Task");
        miDeleteFromAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteFromAllActionPerformed(evt);
            }
        });
        pmDeleteFromAll.add(miDeleteFromAll);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("This Week:");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        liThisWeek.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        liThisWeek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liThisWeek);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("All Tasks");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        liAll.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        liAll.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        liAll.setComponentPopupMenu(pmDeleteFromAll);
        liAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(liAll);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        btExportCSV.setText("Export CSV");
        btExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportCSVActionPerformed(evt);
            }
        });
        getContentPane().add(btExportCSV, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDeleteFromAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteFromAllActionPerformed
        if (liAll.getSelectedIndices().length == 1) {
            int idx = liAll.getSelectedIndex();
            try {
                bl.deleteTask(idx);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong with the database.");
            } catch (IOException io) {
                JOptionPane.showMessageDialog(null, "Preferences are not correct! Look it up in the Project-manual");
            }
            initializeEverything();
        }
    }//GEN-LAST:event_miDeleteFromAllActionPerformed

    private void btExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportCSVActionPerformed
        JFileChooser chooser = new JFileChooser();
        int res = chooser.showOpenDialog(this);
        if(res == JFileChooser.APPROVE_OPTION){
            File saveToFile = chooser.getSelectedFile();
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(saveToFile));
                bw.write("taskname;username;startdate;enddate");
                bw.newLine();
                for (Task task : bl.getTasks()) {
                    bw.write(String.format("%s;%s;%s;%s", task.getTaskName(), task.getUser().getName(), task.getStartDate(), task.getEndDate()));
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                JOptionPane.showMessageDialog(null, String.format("Everything done! Written to the file: %s",saveToFile.getAbsolutePath()));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "There is something wrong with the file!");
            }
        }
    }//GEN-LAST:event_btExportCSVActionPerformed

    private void initializeEverything() {
        dlmAll.removeAllElements();
        dlmThisWeek.removeAllElements();
        for (Task task : bl.getTasks()) {
            if ((task.getStartDate().isAfter(currentWeek.minusDays(1)) && task.getStartDate().isBefore(currentWeek.plusDays(7)))
                    || (task.getEndDate().isAfter(currentWeek.minusDays(1)) && task.getEndDate().isBefore(currentWeek.plusDays(7)))
                    || (task.getStartDate().isBefore(currentWeek.minusDays(1)) && task.getEndDate().isAfter(currentWeek.plusDays(7)))) {
                dlmThisWeek.addElement(task);
            }
            dlmAll.addElement(task);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExportCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> liAll;
    private javax.swing.JList<String> liThisWeek;
    private javax.swing.JMenuItem miDeleteFromAll;
    private javax.swing.JPopupMenu pmDeleteFromAll;
    // End of variables declaration//GEN-END:variables
}
