/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BusinessLogic;
import BL.Task;
import java.time.LocalDate;
import javax.swing.DefaultListModel;

/**
 *
 * @author johannesriedmueller
 */
public class ProductBacklogGUI extends javax.swing.JFrame {

    private BusinessLogic bl;
    private LocalDate currentWeek;
    private DefaultListModel dlmAll = new DefaultListModel();
    private DefaultListModel dlmThisWeek = new DefaultListModel();

    public ProductBacklogGUI(BusinessLogic bl, LocalDate currentWeek) {
        initComponents();
        this.currentWeek = currentWeek;
        this.bl = bl;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        liAll.setModel(dlmAll);
        liThisWeek.setModel(dlmThisWeek);
        initializeEverything();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liThisWeek = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liAll = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("This Week:");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        liThisWeek.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liThisWeek);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("All Tasks");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        liAll.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(liAll);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> liAll;
    private javax.swing.JList<String> liThisWeek;
    // End of variables declaration//GEN-END:variables

    private void initializeEverything() {
        for (Task task : bl.getTasks()) {
            if ((task.getStartDate().isAfter(currentWeek.minusDays(1)) && task.getStartDate().isBefore(currentWeek.plusDays(7)))
                    || (task.getEndDate().isAfter(currentWeek.minusDays(1)) && task.getEndDate().isBefore(currentWeek.plusDays(7)))
                    || (task.getStartDate().isBefore(currentWeek.minusDays(1)) && task.getEndDate().isAfter(currentWeek.plusDays(7)))) {
                dlmThisWeek.addElement(task);
            }
            dlmAll.addElement(task);
        }
    }
}
