/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Task;
import BL.User;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author johannesriedmueller
 */
public class TaskDialog extends javax.swing.JDialog {

    private SpinnerDateModel spinModStart = new SpinnerDateModel();
    private SpinnerDateModel spinModEnd = new SpinnerDateModel();
    private boolean ok = false;
    private Task task;
    private String placeholderName = "Taskname";
    private ArrayList<User> user;

    public TaskDialog(java.awt.Frame parent, boolean modal, ArrayList<User> user) {
        super(parent, modal);
        initComponents();
        this.user = user;
        for (User user1 : this.user) {
            cbUser.addItem(user1);
        }
        tfTaskName.setText(placeholderName);
        jsStartDate.setModel(spinModStart);
        jsEndDate.setModel(spinModEnd);
        jsStartDate.setEditor(new JSpinner.DateEditor(jsStartDate, "dd.MM.yyyy"));
        jsEndDate.setEditor(new JSpinner.DateEditor(jsEndDate, "dd.MM.yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btcancel = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tfTaskName = new javax.swing.JTextField();
        cbUser = new javax.swing.JComboBox<>();
        jsStartDate = new javax.swing.JSpinner();
        jsEndDate = new javax.swing.JSpinner();

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Task creation");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jPanel2.add(btcancel);

        btCreate.setText("Create");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btCreate);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        tfTaskName.setForeground(new java.awt.Color(170, 170, 170));
        tfTaskName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTaskNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTaskNameFocusLost(evt);
            }
        });
        jPanel3.add(tfTaskName);

        jPanel3.add(cbUser);
        jPanel3.add(jsStartDate);
        jPanel3.add(jsEndDate);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePlaceholder(boolean gained, JTextField field, String toSet) {
        if (gained) {
            if (field.getText().equals(toSet)) {
                field.setText("");
                field.setForeground(new java.awt.Color(0, 0, 0));
            }
        } else {
            if (field.getText().equals("")) {
                field.setText(toSet);
                field.setForeground(new java.awt.Color(170, 170, 170));
            }
        }
    }

    public boolean isOk() {
        return ok;
    }

    public Task getTask() {
        return task;
    }


    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        ok = false;
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        try {
            Calendar cal = Calendar.getInstance();
            cal.setTime((Date)jsStartDate.getValue());
            LocalDate startDate = LocalDate.of(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH)+1, cal.get(Calendar.DAY_OF_MONTH));
            cal.setTime((Date)jsEndDate.getValue());
            LocalDate endDate = LocalDate.of(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH)+1, cal.get(Calendar.DAY_OF_MONTH));
            if (tfTaskName.getText().equals(placeholderName)) {
                int res = JOptionPane.showOptionDialog(null, "Do you really want to create a Task with no name?", "Caution!", JOptionPane.YES_NO_OPTION, 1, null, null, null);
                if (res == 0) {
                    User user = cbUser.getItemAt(cbUser.getSelectedIndex());
                    task = new Task("No Taskname", user, startDate, endDate);
                    ok = true;
                    this.dispose();
                }
            } else {
                String name = tfTaskName.getText();
                User user = cbUser.getItemAt(cbUser.getSelectedIndex());
                task = new Task(name, user, startDate, endDate);
                ok = true;
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "There is something wrong with the date");
        }
    }//GEN-LAST:event_btCreateActionPerformed

    private void tfTaskNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTaskNameFocusGained
        updatePlaceholder(true, tfTaskName, placeholderName);
    }//GEN-LAST:event_tfTaskNameFocusGained

    private void tfTaskNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTaskNameFocusLost
        updatePlaceholder(false, tfTaskName, placeholderName);
    }//GEN-LAST:event_tfTaskNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btcancel;
    private javax.swing.JComboBox<User> cbUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jsEndDate;
    private javax.swing.JSpinner jsStartDate;
    private javax.swing.JTextField tfTaskName;
    // End of variables declaration//GEN-END:variables
}
